### ISSUE TITLE
covid-19 dataset

### ISSUE THREAD

**Issue by baiti01** [abdkhanstd/COVID-19#1]
Hi, I am very interesting in the released covid-19 data set, and have downloaded it. But I found that a password is required to unzip it. Would you mind providing me a password for that? Thank you very much. You can reach me via email: tibaiw@gmail.com if you want.

**Comment by Baiyuetribe** [comment]
![image](https://user-images.githubusercontent.com/43716063/88455913-0d3cb300-ceac-11ea-9fa6-8cdcbe9f0c6f.png)
I also want to unzip the password。

**Comment by abdkhanstd** [comment]
The password is "thankyou". Password is updated in readme. Thank you for your interest.

**Comment by abdkhanstd** [comment]
Hi,

The password is "thankyou". Password is also updated in readme. If the dataset or code is helpful, don't forget to cite the relevant paper.

Thank you for your interest.

________________________________
