### ISSUE TITLE
test

### ISSUE THREAD

**Issue by saifmassoud** [abdkhanstd/COVID-19#2]
Hi,
I'm interesting to reproduce your code, but I don't find the Train and test codes of the federated and the global application. Can you help me please?

Thenk you in advance

**Comment by abdkhanstd** [comment]
Dear prestige researcher!

Sorry for late reply. I have discussed the matter with my collogue. Please wait a little while. I will upload the code for the weights as soon we get the response for publication.

Cheers!
________________________________

**Comment by saifmassoud** [comment]
Thank you, and good luck for the publication response

**Comment by King-01** [comment]
Hi,
I am also trying to reproduce your code for academic purposes, can you please complete the code now.
Thanks in advance.
